# Generated by Django 5.0.6 on 2024-05-18 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='authored',
        ),
    ]
